git:
  depth: false
language: rust
cache: cargo
rust:
  - nightly
matrix:
  fast_finish: true
before_install:
  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
scripts:
  - cargo build --verbose --all
  - wasm-pack build js
  - cargo test --verbose --all
